<a href="https://colab.research.google.com/github/CrepinJr/projetpython/blob/main/datahub2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size=6.5 color="sky-blue"><b> <span> Initiation à Python pour la Data Science </span> </b></font>


<font size=5><b> <span> Exercice Séance 2 : </span> </b>  Structure de contrôle et Intro à Numpy</font></center>

##### **Tp à envoyer au plus tard le vendredi 19 janvier à 17h GMT**

In [ ]:
HOUESSOU
Crépin

#### **Exercice 1 (Structures de contrôle if, elif, else)**


1- Écrivez un programme qui demande à l'utilisateur de saisir un nombre, puis affiche "positif", "négatif", ou "zéro" en fonction du nombre saisi.


In [ ]:
num = float(input("Entrez un nombre: "))

if num > 0:
  print('Positif')
elif num == 0:
  print("Zéro")
else :
  print("Négatif")

Entrez un nombre: 1
Positif


2- Créez un programme qui demande à l'utilisateur son âge, puis affiche "mineur", "majeur" ou "senior" en fonction de l'âge.

In [ ]:
num = int(input("Entrez un age: "))

if num >= 0 and num < 18:
  print('Mineur')
elif num>= 18 and num < 50:
  print("Majeur")
elif num >= 50:
  print("Majeur")
else:
  print("Pas un age")

Entrez un age: -6
Pas un age


3- Écrivez un programme qui prend deux nombres en entrée et affiche le plus grand des deux.

In [3]:
num1 = int(input("Entrez le premier nombre : "))
num2 = int(input("Entrez le deuxième nombre : "))

if num1 > num2:
  print(num1, "est le plus grand")
elif num2 > num1:
  print(num2, "est le plus grand")
else:
  print("Les deux nombres sont égaux")

Entrez le premier nombre : -6
Entrez le deuxième nombre : 1
1 est le plus grand


#### **Exercice 2 (Boucle for et while)**

1- Écrivez un programme qui calcule la somme des nombres de 1 à 10 à l'aide d'une boucle for.

In [4]:
somme = 0

for i in range(1, 11):
  somme += i

print("La somme des nombres de 1 à 10 est :", somme)

La somme des nombres de 1 à 10 est : 55


2- Écrivez un programme qui demande à l'utilisateur de deviner un nombre entre 1 et 10. Utilisez une boucle while pour continuer à demander jusqu'à ce que l'utilisateur trouve le bon nombre.

In [5]:
from random import randint

nombre_mystere = randint(1, 10)
trouve = False

while not trouve:
  num = int(input("Devinez le nombre (entre 1 et 10) : "))

  if num == nombre_mystere:
    print("Bravo, vous avez trouvé le nombre mystère !")
    trouve = True
  else:
    print("Désolé, ce n'est pas le bon nombre. Réessayez !")

print("Fin du jeu")

Devinez le nombre (entre 1 et 10) : 1
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 8
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 2
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 3
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 4
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 5
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 6
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 7
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 9
Désolé, ce n'est pas le bon nombre. Réessayez !
Devinez le nombre (entre 1 et 10) : 10
Bravo, vous avez trouvé le nombre mystère !
Fin du jeu


3- Créez une liste de fruits, puis utilisez une boucle for pour afficher chaque fruit.

In [6]:
fruits = ["pomme", "banane", "orange", "fraise", "kiwi"]

for fruit in fruits:
  print(fruit)

pomme
banane
orange
fraise
kiwi


#### **Exercice 3 (Création de Tableaux numpy)**


1- Créez un tableau Numpy 1D avec les entiers de 1 à 5.



In [1]:
import numpy as np

tableau = np.arange(1, 6)

print(tableau)


[1 2 3 4 5]



2- Créez un tableau Numpy 2D (matrice) 2x3 avec des nombres entiers de votre choix.

In [2]:
matrice = np.array([[1, 2, 3], [4, 5, 6]])

print(matrice)

[[1 2 3]
 [4 5 6]]


#### **Exercice 4 (Indexation et Slicing)**

1- Accédez au deuxième élément du tableau 1D.

In [3]:
print(tableau[1])

2


2- Accédez à l'élément situé à la deuxième ligne et troisième colonne du tableau 2D.



In [6]:
element = matrice[1, 2:]
print(element)

[6]


3- Sélectionnez les deux premiers éléments de chaque ligne dans le tableau 2D.

In [7]:
print(matrice[:, :2])

[[1 2]
 [4 5]]


#### **Exercice 5 (Opérations de Base- Numpy)**


1- Ajoutez 5 à chaque élément du tableau 1D.



In [8]:
tableau = tableau + 5
print(tableau)

[ 6  7  8  9 10]


2- Multipliez chaque élément du tableau 2D par 2.


In [9]:
matrice = matrice*2
print(matrice)

[[ 2  4  6]
 [ 8 10 12]]


3- Calculez la somme et la moyenne des éléments du tableau 1D.


In [11]:
somme = tableau.sum()
moyenne = tableau.mean()
print(somme)
print(moyenne)

40
8.0


#### **Exercice 6 : (Filtrage et Conditionnement)**


1- Créez un tableau Numpy 1D de nombres aléatoires entre 1 et 20.





In [12]:
tableau_aleatoire = np.random.randint(1, 21, size=10)

print(tableau_aleatoire)

[ 7 11 14 17  6 17 20 14  2  3]


2- Sélectionnez tous les éléments du tableau qui sont supérieurs à 10.



In [13]:
elements = tableau_aleatoire[tableau_aleatoire > 10]
print(elements)

[11 14 17 17 20 14]


3- Remplacez tous les éléments du tableau inférieurs à 5 par la valeur 0.

In [14]:
tableau_aleatoire[tableau_aleatoire < 5] = 0
print(tableau_aleatoire)

[ 7 11 14 17  6 17 20 14  0  0]


#### **Exercice 7 : (Manipulation de Matrices)**



1- Créez une matrice identité 3x3.



In [15]:
matrice_identite = np.eye(3)
print(matrice_identite)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2- Concaténez horizontalement deux tableaux 1D.



In [20]:
tableau1 = np.array([1, 2, 3])
tableau2 = np.array([4, 5, 6])

tableau_concatene = np.concatenate((tableau1, tableau2), axis=0)

print(tableau_concatene)

[1 2 3 4 5 6]


3- Effectuez une multiplication matricielle entre une matrice 2x3 et un tableau 3x1.

In [21]:
tableau3 = np.array([[1, 2, 3],[4, 5, 6]])

tableau4 = np.array([[7],[8],[9]])
print(np.dot(tableau3, tableau4))

[[ 50]
 [122]]
